# Generated by Django 4.2.20 on 2025-03-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flex',
            name='rank',
        ),
    ]
