# Generated by Django 4.2.20 on 2025-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_flex_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='flex',
            name='rank',
            field=models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('ASCENDANT', 'Ascendant'), ('IMMORTAL', 'Immortal'), ('RADIANT', 'Radiant')], default='IRON', max_length=10),
        ),
    ]
