# Generated by Django 4.2.20 on 2025-03-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_flex_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flex',
            name='nome',
        ),
    ]
