# Generated by Django 4.2.20 on 2025-03-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_flex_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='flex',
            name='nome',
            field=models.CharField(default='insert RiotID', max_length=20),
        ),
    ]
