# Generated by Django 4.2.20 on 2025-03-13 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_flex_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='flex',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
    ]
