# Generated by Django 4.2.20 on 2025-03-13 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_flex_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flex',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
    ]
