# Generated by Django 4.2.20 on 2025-03-13 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_flex_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='insert RiotID', max_length=20)),
                ('team', models.ForeignKey(blank=True, default='LFT', null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team')),
            ],
        ),
    ]
