# Generated by Django 4.2.20 on 2025-03-13 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_duelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentinel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='insert RiotID', max_length=20)),
                ('rank', models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('ASCENDANT', 'Ascendant'), ('IMMORTAL', 'Immortal'), ('RADIANT', 'Radiant')], default='IRON', max_length=10)),
                ('team', models.ForeignKey(blank=True, default='LFT', null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team')),
            ],
        ),
        migrations.CreateModel(
            name='Initiator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='insert RiotID', max_length=20)),
                ('rank', models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('ASCENDANT', 'Ascendant'), ('IMMORTAL', 'Immortal'), ('RADIANT', 'Radiant')], default='IRON', max_length=10)),
                ('team', models.ForeignKey(blank=True, default='LFT', null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team')),
            ],
        ),
    ]
