# Generated by Django 4.2.20 on 2025-03-17 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_sentinel_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
        migrations.AlterField(
            model_name='duelist',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
        migrations.AlterField(
            model_name='flex',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
        migrations.AlterField(
            model_name='initiator',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
        migrations.AlterField(
            model_name='sentinel',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
    ]
