# Generated by Django 4.2.20 on 2025-04-03 13:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_alter_controller_team_alter_duelist_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controller',
            options={'ordering': ['-rank', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='duelist',
            options={'ordering': ['-rank', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='flex',
            options={'ordering': ['-rank', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='initiator',
            options={'ordering': ['-rank', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='sentinel',
            options={'ordering': ['-rank', 'nome']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='controller',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='controller',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='duelist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='duelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flex',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flex',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='initiator',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='initiator',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sentinel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sentinel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='controller',
            name='nome',
            field=models.CharField(default='insert RiotID', help_text='Enter your Riot ID (2-20 characters)', max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='controller',
            name='rank',
            field=models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('ASCENDANT', 'Ascendant'), ('IMMORTAL', 'Immortal'), ('RADIANT', 'Radiant')], default='IRON', help_text='Select your current rank', max_length=10),
        ),
        migrations.AlterField(
            model_name='controller',
            name='team',
            field=models.ForeignKey(blank=True, default='LFT', help_text='Select a team or leave as LFT (Looking For Team)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
        migrations.AlterField(
            model_name='duelist',
            name='nome',
            field=models.CharField(default='insert RiotID', help_text='Enter your Riot ID (2-20 characters)', max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='duelist',
            name='rank',
            field=models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('ASCENDANT', 'Ascendant'), ('IMMORTAL', 'Immortal'), ('RADIANT', 'Radiant')], default='IRON', help_text='Select your current rank', max_length=10),
        ),
        migrations.AlterField(
            model_name='duelist',
            name='team',
            field=models.ForeignKey(blank=True, default='LFT', help_text='Select a team or leave as LFT (Looking For Team)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
        migrations.AlterField(
            model_name='flex',
            name='nome',
            field=models.CharField(default='insert RiotID', help_text='Enter your Riot ID (2-20 characters)', max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='flex',
            name='rank',
            field=models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('ASCENDANT', 'Ascendant'), ('IMMORTAL', 'Immortal'), ('RADIANT', 'Radiant')], default='IRON', help_text='Select your current rank', max_length=10),
        ),
        migrations.AlterField(
            model_name='flex',
            name='team',
            field=models.ForeignKey(blank=True, default='LFT', help_text='Select a team or leave as LFT (Looking For Team)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
        migrations.AlterField(
            model_name='initiator',
            name='nome',
            field=models.CharField(default='insert RiotID', help_text='Enter your Riot ID (2-20 characters)', max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='initiator',
            name='rank',
            field=models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('ASCENDANT', 'Ascendant'), ('IMMORTAL', 'Immortal'), ('RADIANT', 'Radiant')], default='IRON', help_text='Select your current rank', max_length=10),
        ),
        migrations.AlterField(
            model_name='initiator',
            name='team',
            field=models.ForeignKey(blank=True, default='LFT', help_text='Select a team or leave as LFT (Looking For Team)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
        migrations.AlterField(
            model_name='sentinel',
            name='nome',
            field=models.CharField(default='insert RiotID', help_text='Enter your Riot ID (2-20 characters)', max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='sentinel',
            name='rank',
            field=models.CharField(choices=[('IRON', 'Iron'), ('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum'), ('DIAMOND', 'Diamond'), ('ASCENDANT', 'Ascendant'), ('IMMORTAL', 'Immortal'), ('RADIANT', 'Radiant')], default='IRON', help_text='Select your current rank', max_length=10),
        ),
        migrations.AlterField(
            model_name='sentinel',
            name='team',
            field=models.ForeignKey(blank=True, default='LFT', help_text='Select a team or leave as LFT (Looking For Team)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload team logo (optional)', null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='nome',
            field=models.CharField(help_text='Enter the team name (2-20 characters)', max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
