# Generated by Django 4.2.20 on 2025-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_controller_options_alter_duelist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload player image (optional)', null=True, upload_to='player_images/'),
        ),
        migrations.AddField(
            model_name='duelist',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload player image (optional)', null=True, upload_to='player_images/'),
        ),
        migrations.AddField(
            model_name='flex',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload player image (optional)', null=True, upload_to='player_images/'),
        ),
        migrations.AddField(
            model_name='initiator',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload player image (optional)', null=True, upload_to='player_images/'),
        ),
        migrations.AddField(
            model_name='sentinel',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload player image (optional)', null=True, upload_to='player_images/'),
        ),
    ]
